import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import AuthContext from "./auth-context";
import { authOptions } from "./auth-options";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <AuthContext session={session}>
        <body className={inter.className}>{children}</body>
      </AuthContext>
    </html>
  );
}
