import { api } from "../lib/api";
import { Category } from "../api/categories/route";
import CategoryHeaderWrapper from "./category-header-wrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const getCategories = async (): Promise<Category[]> => {
  return api("/api/categories", { cache: "no-store" })
    .then((data) => data.json())
    .then((data) => data["data"]);
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const categories = await getCategories();
  return (
    <div className="p-4">
      <CategoryHeaderWrapper categories={categories} />
      {props?.children}
    </div>
  );
}
